name: Python Packaging
on: [workflow_dispatch]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Virtual Environment
        run: |
          python3 -m pip install --user virtualenv
          virtualenv env_unit_tests
          source ./env_unit_tests/bin/activate

      - name: Install Dependencies
        run: |
          ls -lh
          pip install -r ./aws-chatgpt-telegram/lambda_function/requirements.txt
          
      - name: Package Python
        run: |
          #!/bin/bash
          echo "Executing packaging."

          # Create the packaging directory.
          dir_name=lambda_dist_pkg/
          mkdir $dir_name
          
          # Set up some variables that will be used throughout the packaing process.
          function_name="chatgpt_telegram_package"

          # Installing python dependencies.
          FILE=./lambda_function/requirements.txt
          if [ -f "$FILE" ]; then
            echo "Installing dependencies."
            echo "From: requirement.txt file exists."
            pip install -r "$FILE"
          else
            echo "Error: requirement.txt does not exist!"
          fi

          # Deactivate virtual environment.
          deactivate

          # Create deployment package.
          echo "Creating deployment package."
          cp -r env_$function_name/lib/$runtime/site-packages/. ./$dir_name
          cp -r ./lambda_function/ ./$dir_name
          zip -r $function_name.zip ./$dir_name

          # Removing virtual environment folder.
          echo "Removing virtual environment folder."
          rm -rf ./env_$function_name
          rm -rf ./$dir_name
          echo "Package Built."
        working-directory: ./aws-chatgpt-telegram/
        env:
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
          TELEGRAM_SECRET_TOKEN: "${{ secrets.OPENAI_API_KEY }}"
