name: Python Packaging
on: [workflow_dispatch]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Package Python
        run: |
          echo "Package creation."

          # Create the packaging directory.
          dir_name=lambda_dist_pkg/
          mkdir $dir_name

          # Set up some variables and environment for the packaging.
          function_name="chatgpt_telegram_package"

          python3 -m pip install --user virtualenv
          virtualenv env_$function_name
          source ./env_$function_name/bin/activate

          # Installing python dependencies.
          pip install -r ./lambda_function/requirements.txt

          # Deactivate virtual environment.
          deactivate

          # Create deployment package.
          echo "Creating deployment package."
          cp -r env_$function_name/lib/$runtime/site-packages/. ./$dir_name
          cp -r ./lambda_function/ ./$dir_name
          zip -r $function_name.zip ./$dir_name

          # Removing virtual environment folder.
          echo "Removing virtual environment folder."
          rm -rf ./env_$function_name
          rm -rf ./$dir_name
          echo "Package Built."
        working-directory: ./aws-chatgpt-telegram/
        env:
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
          TELEGRAM_SECRET_TOKEN: "${{ secrets.OPENAI_API_KEY }}"
