name: Python Packaging and Deployment

on:
  workflow_dispatch:
    inputs:
      lambda_function_name:
        required: true
        type: string
        default: "chatgpt-telegram"
  workflow_call:
    inputs:
      lambda_function_name:
        required: true
        type: string

env:
  py_version: '3.10'
  aws_region: af-south-1
