name: Python Test
on: [workflow_dispatch]
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Virtual Environment
        run: |
          python3 -m pip install --user virtualenv
          virtualenv env_unit_tests
          source ./env_unit_tests/bin/activate

      - name: Install Dependencies
        run: |
          ls -lh
          pip install -r ./aws-chatgpt-telegram/lambda_function/requirements.txt
          
      - name: Run Unit Tests
        run: |
          TELEGRAM_TOKEN="${{ secret.TELEGRAM_TOKEN }}"
          OPENAI_API_KEY="${{ secret.OPENAI_API_KEY }}"
          TELEGRAM_SECRET_TOKEN="${{ secret.OPENAI_API_KEY }}"
          python unittests.py
        working-directory: ./aws-chatgpt-telegram/lambda_function/
